- name: Windows | Downloading windows NRPE agent
  win_get_url:
    dest: C:\NSCP-0.5.2.35-x64.msi
    url: "https://github.com/mickem/nscp/releases/download/0.5.2.35/NSCP-0.5.2.35-x64.msi"


- name: Windows | Install NRPE agent
  win_package:
    path: C:\NSCP-0.5.2.35-x64.msi
    arguments: ALLOWED_HOSTS={{ add_node_nagios }} ADDLOCAL=NRPEPlugins NRPEMODE=LEGACY CONF_NRPE=True